version: '3.8'

services:
  mistral_api:
    build:
      context: .
      args:
        HF_TOKEN: "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"
    ports:
      - "5000:5000"
    environment:
      HUGGINGFACE_TOKEN: "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"
    deploy:
      resources:
        limits:
          cpus: '20.0'         # Используйте до 4 vCPU (можно варьировать до 8, если потребуется)
          memory: 20g          # Установите 16 ГБ, оставив запас
        reservations:
          cpus: '2.0'         # Минимум 2 vCPU зарезервированы
          memory: 20g          # Минимум 8 ГБ зарезервировано
