version: '3.8'

services:
  mistral_api:
    build:
      context: .
      args:
        HF_TOKEN: "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"
    ports:
      - "5000:5000"
    environment:
      HUGGINGFACE_TOKEN: "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"
    deploy:
      resources:
        limits:
          cpus: '8.0'         # Ограничим до 8 vCPU для предотвращения избыточного использования
          memory: 16g         # 16 ГБ — почти весь доступный объём RAM, оставляем небольшой запас
        reservations:
          cpus: '4.0'         # Минимум 4 vCPU для обеспечения базовой производительности
          memory: 8g          # Минимум 8 ГБ памяти для более гибкого распределения ресурсов
    restart: always           # Добавим авто-перезапуск на случай падений из-за нехватки памяти
