version: '3.8'

services:
  mistral_api:
    build:
      context: .
      args:
        HF_TOKEN: "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"
    ports:
      - "5000:5000"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4g
