version: '3.8'

services:
  mistral_api:
    build:
      context: .
      args:
        HF_TOKEN: ${HUGGINGFACE_TOKEN}
    ports:
      - "8000:8000"
    environment:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '8.0'     # Максимально доступные CPU
          memory: 16g     # Максимально доступная память
        reservations:
          cpus: '4.0'     # Минимальный резерв CPU
          memory: 8g      # Минимальный резерв памяти
    restart: always       # Автоперезапуск
    volumes:
      - model_cache:/root/.cache/huggingface  # Кэш моделей Hugging Face для оптимизации запуска

volumes:
  model_cache:              # Определение тома для кэша
